# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  SETUP_MAGE_VERSION: '1.15.0'
  SETUP_GVM_VERSION: 'v0.5.0'
  ASDF_MAGE_VERSION: '1.15.0'
  GCP_DEFAULT_MACHINE_TYPE: "c2d-highcpu-8"
  GCP_WIN_MACHINE_TYPE: "n2-standard-8"
  IMAGE_MACOS_X86_64: "generic-13-ventura-x64"
  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"
  IMAGE_WIN_11: "family/platform-ingest-beats-windows-11"

steps:
  - label: ":buildkite: Lint"
    command: |
      set -euo pipefail
      echo "--- Mage notice"
      mage notice
      echo "--- Mage check"
      mage -v check
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
      
  - label: ":linux: Test Linux"
    key: test-lin
    command: |
      set -euo pipefail
      go test -v > output-report-linux.out
    agents:
      provider: "gcp"
      image: "${IMAGE_UBUNTU_X86_64}"
      machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
    artifact_paths:
      - "output-report-*.out"

  - label: ":windows: Test Windows"
    key: test-win
    command: |
      go test -v > output-report-windows.out
    agents:
      provider: "gcp"
      image: "${IMAGE_WIN_11}"
      machine_type: "${GCP_WIN_MACHINE_TYPE}"
      disk_size: 200
      disk_type: "pd-ssd"
    artifact_paths:
      - "output-report-*.out"

  - label: ":pipeline: Process junit reports"
    key: process-junit
    command: |
      set -eo pipefail
      buildkite-agent artifact download "output-report-*.out" .
      for f in output-report-*.out; do
      go-junit-report > "${junitfile:-junit-report-$f.xml}" < "$f"
      done
    agents:
      image: "docker.elastic.co/ci-agent-images/platform-ingest/buildkite-agent-beats-ci-with-hooks:0.1"
      useCustomGlobalHooks: true
    artifact_paths: 
      junit-report-*
    depends_on:
      - step: "test-lin"
        allow_failure: true
      - step: "test-win"
        allow_failure: true

  - label: ":junit: Junit annotate"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "junit-*.xml"
          fail-build-on-error: true
    agents:
      provider: "gcp" #junit plugin requires docker
    depends_on:
      - step: "process-junit"
        allow_failure: true
